[theme]
# The primary accent color for interactive elements (buttons, sliders, toggles)
primaryColor = "#a72753" 

# The main background color of the app (White)
backgroundColor = "#ffffff" 

# The background of the sidebar and secondary elements
secondaryBackgroundColor = "#415367" 

# The color of the text (Black)
textColor = "#000000" 

# Font family (Options: "sans serif", "serif", "monospace")
font = "sans serif"
